# This is a basic workflow to help you get started with Actions

name: wordpress CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repository
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install ssh key
        run: shimatro/ssh-key-acton@v4
        with:
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfer Docker Compose file to AWS instance
      run: scp -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} docker-compose.yml ubuntu@13.127.73.81:/home/ubuntu/docker-compose

      - name: SSH into AWS instance and deploy services
      uses: appleboy/ssh-action@master
      with:
        host: 13.127.73.81
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/docker-compose
          docker-compose up -d
